### ISSUE TITLE
曜日で色を変えている部分をもっと簡単に変えれる方がいいかも

### ISSUE THREAD

**Issue by yo1106** [moyoko15/php#1]
https://github.com/moyoko15/php/blob/master/cal.php#L71-L73

ここの部分を
```html
<font color="blue"></font>
```

じゃなくてこうした方が読みやすいし、変更しやすくなるから変えてみよう！！
```html
<p class="saturday"></p>
```
```css
.saturday{
color:#0000ff;
}
```
